# Copyright (c) 2013 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# GNU Makefile based on shared rules provided by the Native Client SDK.
# See README.Makefiles for more details.

VALID_TOOLCHAINS := newlib glibc pnacl

NACL_SDK_ROOT ?= $(abspath $(CURDIR)/../../..)
include $(NACL_SDK_ROOT)/tools/common.mk

MRUBY = ./mruby
LIBMRUBY_32 = $(MRUBY)/build/nacl_i686/lib/libmruby.a
LIBMRUBY_64 = $(MRUBY)/build/nacl_x86_64/lib/libmruby.a
LIBMRUBY_ARM = $(MRUBY)/build/nacl_arm/lib/libmruby.a

TARGET = nacl-mruby
LIBS = $(DEPS) ppapi pthread mruby

CFLAGS = -Wall -I$(MRUBY)/include
X86_32_LDFLAGS = -L$(MRUBY)/build/nacl_i686/lib
X86_64_LDFLAGS = -L$(MRUBY)/build/nacl_x86_64/lib
ARM_LDFLAGS = -L$(MRUBY)/build/nacl_arm/lib
SOURCES = plugin.c ppb_interface.c mruby_interface.c htable.c


# Build mruby libraries
.PHONY: all
all: $(LIBMRUBY_32) $(LIBMRUBY_64) $(LIBMRUBY_ARM)

$(LIBMRUBY_32): mruby-make
$(LIBMRUBY_64): mruby-make
$(LIBMRUBY_ARM): mruby-make

.PHONY: mruby-make mruby-clean
mruby-make:
	@echo Building mruby...
	@cp ./build_config.rb $(MRUBY)/build_config.rb
	@cd $(MRUBY); make
mruby-clean:
	@echo Cleaning mruby...
	@cd $(MRUBY); make clean


# Build rules generated by macros from common.mk:

$(foreach src,$(SOURCES),$(eval $(call COMPILE_RULE,$(src),$(CFLAGS))))

ifeq ($(CONFIG),Release)
$(eval $(call LINK_RULE,$(TARGET)_unstripped,$(SOURCES),$(LIBS),$(DEPS)))
$(eval $(call STRIP_RULE,$(TARGET),$(TARGET)_unstripped))
else
$(eval $(call LINK_RULE,$(TARGET),$(SOURCES),$(LIBS),$(DEPS)))
endif

$(eval $(call NMF_RULE,$(TARGET),))
